### ISSUE TITLE
Support Rails 6.0

### ISSUE THREAD

**Issue by k-sonoda-biztex** [smartoperation/active_job-disable#3]
# Problem

I couldn't update Rails to 6 for projects containing this library

- [ ] repro.

```
Bundler could not find compatible versions for gem "activejob":
  In Gemfile:
    active_job-disable was resolved to 0.2.1, which depends on
      activejob (>= 5.0, < 6)

    rails (= 6.0.4.3) was resolved to 6.0.4.3, which depends on
      activejob (= 6.0.4.3)
```

# Possible solution

change deps

https://github.com/smartoperation/active_job-disable/blob/dae333aaf41a37e9e3a10c427c8d02c0435ba395/active_job-disable.gemspec#L24

# Consideration

- [ ] ...

**Comment by k-sonoda-biztex** [comment]
For now, the workaround is to use the [forks](https://github.com/smartoperation/active_job-disable/network/members)

**Comment by buzztaiki** [comment]
Would I update it? Or do you want BizteX dev to maintain it?

**Comment by k-sonoda-biztex** [comment]
We plan to fix this in the near future. We'd like to support up to Rails 6.2.
We are considering whether we should become maintainers. I think it is preferable to transfer ownership as it is under the control of our organization.

**Comment by buzztaiki** [comment]
I see. Please ask if you have any problems.

**Comment by buzztaiki** [comment]
You need ownership of https://rubygems.org/gems/active_job-disable/ to release this gem.  If you give me the email address, I'll add it to owners.

**Comment by k-sonoda-biztex** [comment]
Thank you for your cooperation. My address is:
k.sonoda@biztex.co.jp

**Comment by buzztaiki** [comment]
Sorry, I Could not add k.sonoda@biztex.co.jp to gem's owner. I think that you should create an account on rubygems.org.

**Comment by k-sonoda-biztex** [comment]
I didn't understand the mechanism for publishing. I have created my account. https://rubygems.org/profiles/KenSonodaBizteX

**Comment by buzztaiki** [comment]
Thank you for your account information. I added your account to owner. Confirmation mail will be sent to you.

**Comment by buzztaiki** [comment]
> I didn't understand the mechanism for publishing.

To publish new version, please follow these steps:

1. bump the [version](https://github.com/smartoperation/active_job-disable/blob/dae333aaf41a37e9e3a10c427c8d02c0435ba395/lib/active_job/disable/version.rb#L3)
2. push your changes.
3. run `bundle exec rake release`.

`rake release` will create a local tag, push the tag to remote, and push the gem to rubygems.org. maybe..

**Comment by buzztaiki** [comment]
see https://bundler.io/v2.2/guides/creating_gem.html#releasing-the-gem

**Comment by k-sonoda-biztex** [comment]
Thank you for the detailed explanation.

**Comment by k-sonoda-biztex** [comment]
https://rubygems.org/gems/active_job-disable/versions/0.3.0
